#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt with apfree-wifidog using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Contributed: digitcloud
# Modified: liudf0716
#=================================================

name: Build OpenWrt with apfree-wifidog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      openwrtBranch:
        description: 'input openwrt branch'
        required: true
        default: 'openwrt-19.07'
      configFile:
        description: 'input openwrt config file name'
        required: true
        default: '.config'

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  FEEDS_CONF: feeds.conf.default
  APFREEWIFIDOG: apfreewifidog.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: checkout
      uses: liudf0716/checkout@v2.3.4

    - name: initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone  $REPO_URL -b ${{ github.event.inputs.openwrtBranch }} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: add third-party feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default 

    - name: update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: load custom configuration
      run: |
        [ -e ${{ github.event.inputs.configFile }} ] && mv ${{ github.event.inputs.configFile }} openwrt/.config
        chmod +x $APFREEWIFIDOG
        cd openwrt &&  package/
        cd openwrt && $GITHUB_WORKSPACE/$APFREEWIFIDOG
    
    - name: download package
      run: |
        cd openwrt
        make download -j4
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
   
    - name: Compile Tools
      id: tools
      if: steps.download.conclusion  == 'success'
      run: |
        cd openwrt
        make tools/compile -j4
          
    - name: Compile Toolchain
      id: toolchain
      if: steps.tools.conclusion == 'success'
      run: |
        cd openwrt
        make toolchain/compile -j4
      
    - name: Compile package apfree-wifidog
      id: compile
      if: steps.toolchain.conclusion  == 'success'
      run: |
        cd openwrt
        make diffconfig
        make package/apfree-wifidog/compile V=s
        echo "::set-output name=status::success"
 
    - name: move target file to download
      id: mk-dl
      run: |
        cd openwrt
        mkdir -p bin/downloads
        cp bin/targets/x86/64/*.gz bin/downloads/
        cp bin/packages/x86_64/packages/apfree-wifidog*.ipk bin/downloads/
        cp dl/apfree-wifidog* bin/downloads/

    - name: upload bin directory
      uses: liudf0716/upload-artifact@v2.2.2
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
         name: openwrt_apfree_wifidog_dl
         path: openwrt/bin/downloads

